### ISSUE TITLE
编译时出现问题

### ISSUE THREAD

**Issue by Agoines** [ztc1997/android_kernel_xiaomi_sm6150#6]
DTC     arch/arm64/boot/dts/qcom/sa6155.dtb
  CC      drivers/media/v4l2-core/v4l2-compat-ioctl32.o
  DTC     arch/arm64/boot/dts/qcom/sa6155p.dtb
  DTC     arch/arm64/boot/dts/qcom/sdmmagpie-atp-overlay.dtbo
Error: ../arch/arm64/boot/dts/qcom/sdmmagpie-thermal-overlay.dtsi:15.1-15 syntax error
FATAL ERROR: Unable to parse input tree
make[3]: *** [scripts/Makefile.dtbo:24: arch/arm64/boot/dts/qcom/sdmmagpie-atp-overlay.dtbo] Error 1
make[2]: *** [../scripts/Makefile.build:676: arch/arm64/boot/dts/qcom] Error 2
make[1]: *** [arch/arm64/Makefile:226: dtbs] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by ztc1997** [comment]
请确保使用的是aosp项目的dtc，而不是apt/yum安装的dtc。

**Comment by Agoines** [comment]
> 请确保使用的是aosp项目的dtc，而不是apt/yum安装的dtc。

已解决，谢谢大佬
